### ISSUE TITLE
Set user agent for bgp.tools table.txt pull

### ISSUE THREAD

**Issue by benjojo** [NLNOG/irrexplorer#112]
Hi there!

bgp.tools has made the table.txt/jsonl endpoint official now. But with a requirement for the user agent to not be a default one. Right now irrexplorer uses `Python/3.9 aiohttp/3.7.4`. Could this be changed to something like "NLNOG - irrexplorer" or something similarly descriptive? 

I've banned default library user agents right now, but special caused the one above that irrexplorer is using until you can hopefully set a custom one!

Thanks again for this great tool

**Comment by teunvink** [comment]
Hey @benjojo, thanks for that! Just to be clear, is this request for the irrexplorer code (so everyone who installs it can use this) or for the https://irrexplorer.nlnog.net website (the irrexplorer setup hosted by NLNOG)?

**Comment by benjojo** [comment]
Either! As long as it has a user agent that can be identified if it needs
upgrading or is going wrong :)

**Comment by teunvink** [comment]
Ok, I'll see what we can do!
