### ISSUE TITLE
Incorrect(?) display of RPKI invalid?

### ISSUE THREAD

**Issue by midco-gitter** [NLNOG/irrexplorer#125]
Right now https://irrexplorer.nlnog.net/asn/AS26823 shows RPKI invalid.

I've downloaded and attached the JSON output.

It looks as though an RADB route object with a different origin is incorrectly been marked as RPKI invalid.

The JSON correctly shows that there is a valid ROA matching the announcement.

**Comment by job** [comment]
@midco-gitter I guess the output is a bit confusing, but what the “RPKI Invalid” label refers too is the RADB route object for which *no* covering RPKI ROA exists to permit it.

The IRR object with `origin: AS26794` is not RPKI valid, because the ROA *only* permits AS 26823 as valid BGP Origin.

**Comment by midco-gitter** [comment]
Thanks.  I think I now see the logic.

For folks looking for a quick good/bad indication the current display is probably confusing.  
It might be worth making the reduced colour mode the default.
