### ISSUE TITLE
Stuck resource for 103.10.232.0/24 that doesn't reflect reality

### ISSUE THREAD

**Issue by thegushi** [NLNOG/irrexplorer#156]
Found while running an IRRExplorer query for AS1280, there's a block:

103.10.232.0/24 | APNIC |   |   | 1280 | Route objects exist, but prefix not seen in DFZ No (covering) RPKI ROA found for route objects

Drilling down to the apnic registry yields:

whois -h whois.apnic.net 103.10.232.0/24

route:          103.10.232.0/24
origin:         AS1280
descr:          APNIC Research and Development
                6 Cordelia St
mnt-by:         MAINT-AU-APNIC-GM85-AP
last-modified:  2018-11-30T00:16:42Z
source:         APNIC

Except that that whois query does not yield that.  I suspect IRRexplorer has it cached somehow and there's no way to force a clear.  (This has been like this for more than a week).

**Comment by teunvink** [comment]
This problem seems to be specifically related to the hosted version on https://irrexplorer.nlnog.net, my local copy doesn't show this.

There were a large number of old entries in the database. I've cleaned it, things seem to be better now.
