### ISSUE TITLE
Feature Suggestion - Link to Queries on Itens on other Columns - RIR, RPKI, IRR Database.

### ISSUE THREAD

**Issue by fischerdouglas** [NLNOG/irrexplorer#172]
On the Interface of IRR Explorer, after doing a query, when the prefixes are presented, putting mouse the mouse over the prefixes listed, it has a link to a query on irrexplorer itself pointing to a query to that specific prefix.
When you put the mouse over the itens on the "BGP" column of each line of prefix, it has a link to Looking Glass of NLNOG.

That is GREAT! And make the analysis of "what is wrong with this prefix) a lot easier.

The suggestion is to do the same with the other columns.

I really don't know what the best target is to point the links, but I brought some suggestions:

To "RIR" column
--------
Maybe a link that points to the Web-Whois or RDAP of the referred RIR.
For example to the 8.8.8.8/24, as it is from ARIN the link could be to https://search.arin.net/rdap/?query=8.8.8.0/24
Or to 200.3.12.0/22, as it is from LACNIC the link could point https://rdap-web.lacnic.net/rdap/ip/200.3.12.0/22

To "RPKI" column
--------
Maybe the link could point to the Routinator hosted by the NetLabs itself. Exemples:
8.8.8.8/24 -> https://routinator.nlnetlabs.nl/8.8.8.0%2F24/15169
200.3.12.0/22 https://routinator.nlnetlabs.nl/200.3.12.0%2F22/28001

To IRR Database columns "RADB", "TC", "ALTDB"
--------
That the hardest to suggest something!
Not all the IRR databases have web interface supporting queries.
(If all of them were using IRRDv4, this could point to the GraphQL interface... but by now, this is just a dream.)

So, my initial suggestion is the link that all of them would point to the query interface o RADB.
And specifying the database as part of the html route.
8.0.0.0/9 | LEVEL3 -> https://radb.net/query?advanced_query=1&keywords=8.0.0.0%2F9&-i+option=&-s=1&db=LEVEL3
8.8.8.0/24 | RADB -> https://radb.net/query?advanced_query=1&keywords=8.8.8.0%2F24&-i+option=&-s=1&db=RADB
200.3.12.0/22 | RADB -> https://radb.net/query?advanced_query=1&keywords=200.3.12.0%2F22&-i+option=&-s=1&db=RADB

I know that what was suggested is not quick to do...
But it is a beginning.

**Comment by fischerdouglas** [comment]
As a complementary sugestion...
I remenber that in some of the several engines of Web Looking Glass existent, exists one that when you hold the mouse on some specific objects, it pops a balloon with the text result a whois of that object.

**Comment by fischerdouglas** [comment]
My objective with this suggestion is to extend even more the idea of IRRExplorer.
Concentrate as much as possible on a single point of the information needed to troubleshoot some BGP Routing Filter Issue.

**Comment by mxsasha** [comment]
Discussion: in the IRR object text popup add a note that this info is mirrored, so perhaps modified and delayed, and add a link back to the authoritative IRR source (new config option per IRR db). If no link is available, skip that.
