### ISSUE TITLE
AFRINIC IRR column not showing for 2001:4200::/32 (and smaller)

### ISSUE THREAD

**Issue by hooligan-sa** [NLNOG/irrexplorer#181]
When checking prefixes for my 2001:4200::/32 and more specific ranges, the IRR source AFRINIC doesn't appear in the list of IRRs, and the 'Advice' column says "Expected route object in AFRINIC, but only found in other IRRs", despite the route6 object existing in AFRINIC's IRRDB. 

From whois -h whois.afrinic.net:  
% Information related to '2001:4200::/32AS2018'

route6:         2001:4200::/32
descr:          MAINTAINED BY TENET
origin:         AS2018
mnt-by:         TNET-MNT01
source:         AFRINIC # Filtered

This isn't the case for all IPv6 prefixes from AFRINIC, specifically tested their own website/prefix 2001:42d0::/40. 

Any chance someone can look into why this is happening?

![No AFRINIC IRR in list](https://user-images.githubusercontent.com/21081291/180427588-37221b96-4e68-4854-ab2d-c7da74da2769.png)

![AFRINIC IRR for other AFRINIC prefixes](https://user-images.githubusercontent.com/21081291/180427580-28fceafe-c982-42af-a168-7a692b1885b9.png)

**Comment by teunvink** [comment]
Not sure what happened here (no hints in logfiles unfortunately), but the whois import from AFRINIC needed a full reload of data. It seems to be OK now, the 'Expected route object in AFRINIC, but only found in other IRRs' is gone.
