### ISSUE TITLE
Frequency of IRR bases retrieving

### ISSUE THREAD

**Issue by fischerdouglas** [NLNOG/irrexplorer#191]
Initially:
I would like to ask how often the irrexplorer.nlnog.net backend retrieves the IRR bases.
And if possible also know what times (in respective timezones) this happens.

Furthermore:
I would like to ask if it is possible to increase this frequency.

From what I could infer, this data acquisition occurs every 24 hours. Which was a reasonable frequency in the past.
But in current times, where you can see changes being replicated in less than 30 minutes between the bases, having to wait those 24 hours generates a certain despair in colleagues to whom I have recommended always checking "if everything is green in irrexplorer".

**Comment by teunvink** [comment]
Sorry for the delay in this reply. Data isn't updated on a schedule, it's a process running in a loop. So there's no way to increase the frequency by adjusting scheduling. We're working on improving the visibility of the age of data (#81). 

I'll leave this ticket open for now to see if we can find ways to improve this (if the freshness output shows this is an issue once this feature is released).

**Comment by teunvink** [comment]
Since we don't do scheduled refreshes this isn't something we can improve. We have better information now on the freshness of data and the process of importing data has been improved so it doesn't hang so often anymore. 

Therefor I'm closing this ticket.
