### ISSUE TITLE
Consistent terminology: BGP vs DFZ

### ISSUE THREAD

**Issue by mxsasha** [NLNOG/irrexplorer#204]
We currently mix the terms BGP and DFZ in the [report](https://github.com/NLNOG/irrexplorer/blob/main/irrexplorer/api/report.py). The table header is called BGP. We should pick one best term and stick with it consistently.

**Comment by forkwhilefork** [comment]
BGP is a protocol, and the DFZ is the current state of one very large instance of that protocol on which irrexplorer is reporting. I think DFZ is the appropriate term here.

**Comment by mxsasha** [comment]
Discussed: we'll use BGP. While DFZ _might_ be technically more correct, but BGP is clearer for more users.

**Comment by PenelopeFudd** [comment]
I'm a newbie.  Here's my 2¢'s worth:

- What do the letters DFZ even stand for?
- In the report, the advice tags are nice, in that they are colour-coded to indicate info/warning/error.
- However, the advice tags could be written in Urdu for all the sense they make at this point in my learning curve.

- Another ticket suggested adding tooltips to the advice tags; I'd suggest including two links with every advice tag:
    - A link explaining in extremely basic detail what the advice tag means
    - An info link showing the data triggering that advice tag:
          - Showing the steps to fix the problem 
          - Showing commands for retrieving that data again, to see if it's fixed
     - The  "Source data as JSON" link is a step in the right direction as far as showing the data, but it doesn't include the commands.  For instance, can `whois` be used here?

The problem, as I see it, is that the advice tags are helpful mnemonics only if you already live and breathe this stuff. 😃 

One thing I recently saw on a documentation site that impressed me was this; perhaps you could adopt it too:

> Have an improvement suggestion for this page? Select the text that could be improved and press Ctrl+Enter to send it to the editors.

Thanks!

**Comment by teunvink** [comment]
Thanks for your feedback. We'll take it into consideration, but since most of the feedback isn't directly related to this issue, and the actual issue has been resolved, I'm closing this one.
