### ISSUE TITLE
https://irrexplorer.nlnog.net/static/dumps/arin-whois-originas.json.bz2 missing

### ISSUE THREAD

**Issue by yaneti** [NLNOG/irrexplorer#218]
This is probably the wrong place to mention this but the arin-whois-originas dump on your nlnog.net hosted instance has been missing for the last week or so with 404 Not found error. And looking at the history its not being generated since 5th of November.

Perhaps you've decided you not host the data in this format any more ? which would be perfectly understandable. Or it has a new place ?

Thanks for providing the service for free so far

**Comment by job** [comment]
That data source has been scheduled for deprecation by the ARIN Advisory Council and Board of Trustees, see https://www.arin.net/participate/policy/drafts/2021_8/ for more information.

it’s probably best to switch to use RPKI and/or IRR and not rely on this data source

**Comment by yaneti** [comment]
I see. Thanks for the pointer and sorry for the noise.
