### ISSUE TITLE
The site irrexplorer.nlnog.net won't open guys.

### ISSUE THREAD

**Issue by MrSaeid007** [NLNOG/irrexplorer#251]
Hi irrexplorer team.

Your site won't open.
Any outage?

**Comment by teunvink** [comment]
Yes, there was a database issue. The site is up and running again now.

**Comment by MrSaeid007** [comment]
> Yes, there was a database issue. The site is up and running again now.

Seems like the website is down again. 👀

**Comment by teunvink** [comment]
Yes, we had to do some additional fixes on the database, it's back now.

**Comment by MrSaeid007** [comment]
> Yes, we had to do some additional fixes on the database, it's back now.

The website is open but the screen is white. Please check.
