### ISSUE TITLE
Outdated / Stale whois information still shown

### ISSUE THREAD

**Issue by stevejost** [NLNOG/irrexplorer#252]
Hello,
I have found an issue with the prefix 199.233.129.0/24 where stale information is shown on the irrexplorer page.  This is similar to the issue #148 where the subnet's whois information was out of date.  

What is shown on the page is an incorrect irr entry originating from level3 which has now been removed:

### From IRRExplorer
whois -h rr.Level3.net 199.233.129.0/24

route:          199.233.129.0/24
descr:          webh block 1
origin:         AS7381
mnt-by:         SGNS-MNT
changed:        noc@sgns.net 20170620
source:         LEVEL3

### Reality
whois -h rr.Level3.net 199.233.129.0/24
route:          199.233.129.0/24
origin:         AS397045
descr:          D. Brown Management
                PO BOX 1296
                Lodi CA 95241
                United States
member-of:      RS-DBMGMT
admin-c:        IPADM694-ARIN
tech-c:         JOSTS-ARIN
tech-c:         NOC31826-ARIN
mnt-by:         MNT-DBM-28
created:        2023-05-10T01:57:55Z
last-modified:  2023-05-11T01:22:41Z
source:         ARIN

**Comment by MattKobayashi** [comment]
@stevejost What you're seeing here is a route object in the LEVEL3 IRR database (I'm guessing an outdated one at that). You'll need to contact LEVEL3 and ask them to remove the route object. Contact details for each IRR database can be found [here](https://www.irr.net/docs/list.html).

**Comment by teunvink** [comment]
We currently are experiencing some database issues that result into some records not properly updating. We're working on getting this resolved, but it will take some more time unfortunately.

**Comment by teunvink** [comment]
we've switch to a different backend server which properly updates, so this problem should be resolved now.
