### ISSUE TITLE
Status page returns 404

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#253]
When clicking the "Data source status" link from the homepage or the results page we get to see a nice overview of the freshness of all data. However, directly linking to `<site>/status` fails, as does reloading the statuspage once it's opened. The status API page works as expected.

Demo setup can be found on https://irrexplorer.teun.tv/, relevant irrexplorer HTTP server log entry:

```
INFO:     xxx.xxx.xxx.xxx:0 - "GET /status/ HTTP/1.0" 404 Not Found
```

This is tested on a fresh install running today's git checkout of irrexplorer code.

**Comment by accuris-infrastructure** [comment]
Can confirm the same on a fresh install using latest code.

**Comment by accuris-infrastructure** [comment]
Just did a bit more testing, appears to only be an issue when calling the `/status/` path directly.

i.e. going to https://irrexplorer.accuris.ca/status/ will return the 404 not found error, however selecting "Data source status" on the homepage of IRRexplorer loads the page fine as when going through that method it seems to call the following endpoint:

```
INFO:     xx.xx.xx.xxx:0 - "GET /api/metadata/ HTTP/1.0" 200 OK
```

**Comment by teunvink** [comment]
Fixed in code, will be deployed on irrexplorer.nlnog.net soon.
