### ISSUE TITLE
Incorrect link URLs for members of an AS-SET

### ISSUE THREAD

**Issue by jbartig** [NLNOG/irrexplorer#256]
[Pulll request #206](https://github.com/NLNOG/irrexplorer/pull/206) added links to members of an AS-SET.  AS-SET members can be other AS-SETs or ASNs.  The links work for AS-SET  members, but they do not work for ASN members of the AS-SET.  The generated links all have the format `/query/`, which only appears to accept an AS-SET.

**Comment by teunvink** [comment]
I have a hard time reproducing this problem, for example all members of AS12859:AS-BIT (both ASNs and AS-SETs) work. Can you give an example where you don't see the expected results?

**Comment by jbartig** [comment]
Using your example of [https://irrexplorer.nlnog.net/as-set/AS12859:AS-BIT](https://irrexplorer.nlnog.net/as-set/AS12859:AS-BIT), I initially also could not reproduce the problem I reported.  From that page, if I clicked on an AS-SET or an AUT-NUM member of the AS-SET, I was directed to the correct page.

What I didn't realize when I opened this issue is that there was a javascript event handler taking action on my clicking of the links to members such as AS-FORMICIDAE and AS1200.  This results in determining the correct type of query to perform for an AS-SET or AUT-NUM member.

What I think I did when I had this issue is rather than simply clicking on the links to the AS-SET members, I instead was right clicking and selecting either open link in a new tab or a new window.  This does not work for AS-SET or AUT-NUM.  The link URLs that are rendered on the [page](https://irrexplorer.nlnog.net/as-set/AS12859:AS-BIT) for the two example members above are:

https://irrexplorer.nlnog.net/query/AS-FORMICIDAE
https://irrexplorer.nlnog.net/query/AS1200

Both of these URLs result in a "Not Found" response.

If I simply click on the links for AS-FORMICIDAE and AS1200, the javascript directs me instead to

https://irrexplorer.nlnog.net/as-set/AS-FORMICIDAE
https://irrexplorer.nlnog.net/asn/AS1200

Could these URLs be rendered by the javascript instead of the non-functional /query/ URLs?

**Comment by teunvink** [comment]
Thanks for the detailed explanation!
