### ISSUE TITLE
IRR explorer front end crashes on large AS-SETs

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#262]
IRR explorer seems to have problems expanding large AS-sets. One we observed which seems to cause issues on multiple instances is `AS-ALSARD-SET`. The IRR explorer webpage is unresponsive as a result of opening that AS-SET.

**Comment by nbakker** [comment]
Possibly related to irrd timing out and closing the TCP connection with irrexplorer not handling that gracefully.

**Comment by mxsasha** [comment]
Duplicate of #193
