### ISSUE TITLE
UI suggestion: make 'supernet' information optional

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#281]
The supernet table on the results page appears to generate confusion for some users, especially with large supernets with a lot of delegations which possibly have issues, but aren't related to the actual prefix being checked. 

Making showing this information optional and not the default could help.

**Comment by teunvink** [comment]
Possibly it helps to reverse the sort order for the supernets, starting with the most specific prefix.

**Comment by mxsasha** [comment]
Discussion: under "directly overlapping", when the search is for IP/prefix, sort the table by prefix size, most specific first.

**Comment by forkwhilefork** [comment]
Looks like a change was made here and then reverted - I would still like the option to disable this (ideally by default) as it adds a lot of information to the page that I don't think I've ever actually wanted.
