### ISSUE TITLE
Website IPv6 availability 

### ISSUE THREAD

**Issue by tiagogaspar8** [NLNOG/irrexplorer#343]
Hi all,

Currently this awesome project hosted on irrexplorer.nlnog.net is available only via IPv4, with no IPv6 address associated with it's record DNS.

Is it possible to add IPv6 support to the website, if I can provide help I'd love to!

Thanks!

**Comment by job** [comment]
I've added an AAAA record https://internet.nl/site/irrexplorer.nlnog.net/2787306/

**Comment by tiagogaspar8** [comment]
God damn, awesome job, thanks!
