### ISSUE TITLE
 Registro.BR Prefixes - "Expected route object in LACNIC"

### ISSUE THREAD

**Issue by fischerdouglas** [NLNOG/irrexplorer#64]
I liked the new resource of saying from which RIR is the IP Block.

And, in general, expecting that the equivalent IRR object exists on the RIR IRR makes sense...
But, in case of prefixes assigned by Registro.BR, it doesn't fit!

Just remembering, Registro.BR(NIC.BR) is a NIR delegated by LACNIC.

Numeric Resource Owners at Registro.BR cannot (at least until now) create IRR Objects at LACNIC IRR.
So, in those cases, the message "Expected route object in LACNIC, but only found in other IRRs" does not reflect the true.

An additional suggestion is that, beyond the RIR, that column extends until NIR/LIR assignations.

**Comment by job** [comment]
Good point!

**Comment by mxsasha** [comment]
Good point, yes. Do you know good data sources for this? I was looking in https://ftp.registro.br/pub/numeracao/ but not really clear on whether that has something we need for this.

**Comment by fischerdouglas** [comment]
Maybe @rubenskuhl could point in right direction.

**Comment by rubenskuhl** [comment]
While this is true, I couldn't find the LACNIC docs stating that loud and clear. One indeed can look at https://ftp.registro.br/pub/numeracao/origin/ for the .br IP allocations or at the REGISTROBR source in both NTT and TC IRRs and verify that while they are in LACNIC's delegated-latest list, they do not appear at LACNIC IRR and can't.

**Comment by job** [comment]
To be specific - this is the file we can periodically fetch and use to construct the equivalent of the NIC.BR IRR ftp://ftp.registro.br/pub/numeracao/origin/nicbr-asn-blk-latest.txt

The format is as following:

```
Origin AS | Company name | Member ID (can be ignored) | < Prefix1 | Prefix2 | Prefix3 | ... >
```

The above can be interpreted as following:

```
route: Prefix1
descr: Company name
origin: Origin AS
source: NICBR

route: Prefix2
descr: Company name
origin: Origin AS
source: NICBR

route: Prefix2
descr: Company name
origin: Origin AS
source: NICBR
```
