### ISSUE TITLE
Redirect nlnog searches

### ISSUE THREAD

**Issue by bluikko** [NLNOG/irrexplorer#71]
The site root irrexplorer.nlnog.net redirects to irrexplorer.dashcare.nl but searches do not.

For example http://irrexplorer.nlnog.net/search/112 could redirect to https://irrexplorer.dashcare.nl/asn/112 (or should it be https://irrexplorer.dashcare.nl/asn/AS112?) and then direct links to irrexplorer searches would not be broken.

Maybe some regex magic is needed in the redirects with the separate `/asn/` and `/prefix/` URLs in the new irrexplorer searches?

**Comment by teunvink** [comment]
@bluikko: I think this has been resolved now that irrexplorer.nlnog.net isn't redirecting to the dashcare site anymore?

**Comment by bluikko** [comment]
> @bluikko: I think this has been resolved now that irrexplorer.nlnog.net isn't redirecting to the dashcare site anymore?

Indeed, the URL like https://irrexplorer.nlnog.net/asn/112 works now. I guess the old `/search` was discontinued.
