### ISSUE TITLE
Show last update of different data sources

### ISSUE THREAD

**Issue by mxsasha** [NLNOG/irrexplorer#81]
It would be nice to have a page that shows when the different data sources were last updated.

- For RIRstats and BGP we currently don't track this, but not too hard to record it in the database.
- For IRRd we might be able to get enough from !J queries. That may only be "last time this database sent us an update" vs "last time we checked for updates" but for users that probably is fine as long as it's clear.
- Needs clear communication, e.g. for RIRstats we can know when we last imported it, but when the file was last generated by the RIR is more complex. Maybe we can offer links to the files we use.

**Comment by teunvink** [comment]
This status page should be linked from the FAQ with an additional explanation in the FAQ on how data is gathered and that data is not realtime.
