### ISSUE TITLE
Add support for persistent links to results

### ISSUE THREAD

**Issue by mxsasha** [NLNOG/irrexplorer#82]
Currently all users always see the latest results. If one user sees something, forwards it to someone else, and they open it, they might see something entirely different if the data changed in the mean time. This is sometimes desirable, but it would be nice if users could share links that show what they saw at the time, i.e. create a persistent link to results for a particular query at a particular time.

First idea would be to do this at the API level. It would also implicitly create caching, because if a user (or many users) look up a persistent result page, we don't need to recalculate the result - just retrieve it from the database. However, many pages consist of multiple API calls, which makes this harder.

(discussed earlier with Job, but was out of scope for initial development)

**Comment by teunvink** [comment]
After some discussion we decided that this functionality is not needed, given the options of creating screenshots/pdf's of a webpage.
