### ISSUE TITLE
"raw" HTML markup in error message

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#90]
irrexplorer.nlnog.net seems to be a bit overloaded at this moment. When the backend isn't available in time, the error message shown is, "raw" HTML code is shown as can be seen in the image. It would be nice to show a properly formatted error message.

<img width="848" alt="Screenshot 2021-09-03 at 15 37 12" src="https://user-images.githubusercontent.com/540135/132014485-cecff775-f287-4da6-861a-a1b55bd4d0e0.png">

**Comment by ValZapod** [comment]
It is still better than what I used on before on previous irrexplorer.dashlink.nl.  Try to load AS0, for example.

**Comment by mxsasha** [comment]
Discussion: only fix if it's easy, it's really rare.
