### ISSUE TITLE
Feature Suggestions: route-set Functionality along with AS-SET and route-set raw records viewable

### ISSUE THREAD

**Issue by keatonaglair** [NLNOG/irrexplorer#96]
Simply some suggestions based on my own usage,

I would love to see a functionality similar to AS-SETs but for route-sets, I have route sets that I would love to be able to quickly check for issues and consistency across IRRdbs.

Additionally, I would love to be able to quickly view the raw record for a AS-SET (and route-set if that gets added) similar to clicking on a ASN when viewing the line for a specific subnet (maybe make the link on the RIR name?).

I am aware that at least the former would likely not be easy to implement. I am not a programmer (as #58 is evidence of), if I did possess the ability to implement these changes I would simply submit a pull request. As I prefaced, simply some suggestions, not a problem if none of these get acted upon.

**Comment by mxsasha** [comment]
Discussion: I still need to look into the IRRD options for route-set resolving. The idea of quick view of raw as-set is deferred for now.
